galaxy_info:
  author: Isaac Diamond
  description: Generates certs for workers and controllers

  min_ansible_version: 1.2

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
